[build]
  base = "sandraportfolio"
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  # Do not force redirects. For SPAs, Netlify will serve existing files first.
