[build]
  base = "sandraportfolio"
  command = "npm run build"
  publish = "sandraportfolio/dist"
  functions = "sandraportfolio/netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
